---
- name: Create dirs
  become: yes
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ beacon2ri_user }}"
    group: "{{ beacon2ri_user }}"
    mode: 0755
  loop:
    - "{{ beacon2ri_root }}"

- name: Info¦ beacon2ri_root
  ansible.builtin.debug:
    msg: "{{ beacon2ri_root }}"

