---
- name: Create dirs
  become: yes
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ beacon2ri_user }}"
    group: "{{ beacon2ri_user }}"
    mode: 0755
  loop:
    - "{{ beacon2ri_root }}"

- name: Info¦ beacon2ri_root
  ansible.builtin.debug:
    msg: "{{ beacon2ri_root }}"
  
- name: Fetch¦ beacon2ri code / envs from git
  become: yes
  become_user: "{{ beacon2ri_user }}"
  ansible.builtin.git:
    repo: "{{ beacon2ri_uri }}/{{ item }}"
    dest: "{{ beacon2ri_root }}/{{ item }}"
    force: "{{ force | default(omit) }}"
  loop:
    "{{ beacon2ri_components }}"
  environment:
    GIT_SSL_NO_VERIFY: true
