---
- name: Create dirs
  become: yes
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ beacon2ri_user }}"
    group: "{{ beacon2ri_user }}"
    mode: 0755
  loop:
    - "{{ beacon2ri_root_prefix }}"

- name: Info¦ beacon2ri_base_url
  ansible.builtin.debug:
    msg: "{{ beacon2ri_base_url }}"

# - name: Fetch Modules
#   become: yes
#   ansible.builtin.get_url:
#     url: "{{ beacon2ri_base_url }}"
#     dest: "{{ beacon2ri_download_dir }}"
#     owner: "{{ beacon2ri_user }}"
#     group: "{{ beacon2ri_user }}"
#     mode: 0750

# - name: Extract beacon2ri release binaries
#   become: yes
#   register: binaries_extracted
#   ansible.builtin.unarchive:
#     remote_src: true
#     list_files: yes
#     owner: "{{ beacon2ri_user }}"
#     group: "{{ beacon2ri_user }}"
#     src: "{{ beacon2ri_base_url }}"
#     dest: "{{ beacon2ri_build_dir }}/"

# - name: Info¦ extracted binaries?
#   ansible.builtin.debug:
#     msg: "{{ binaries_extracted }}"

# - name: Build¦ make clean
#   become: yes
#   become_flags: "-u {{ beacon2ri_user }}"
#   args:
#     chdir: "{{ beacon2ri_build_dir }}/{{ binaries_extracted.files[0] }}"
#   ansible.builtin.shell:
#     make clean || true

# - name: Build¦ configure beacon2ri src
#   become: yes
#   become_flags: "-u {{ beacon2ri_user }}"
#   args:
#     chdir: "{{ beacon2ri_build_dir }}/{{ binaries_extracted.files[0] }}"
#     # creates: "lib/config.log"
#   ansible.builtin.command: >
#     ./configure --prefix {{ beacon2ri_root_prefix }}/beacon2ri
#       --enable-versioning
#       --enable-set-shell-startup
#       --enable-quarantine-support

# - name: Quirks¦ Fix src file perms ( root files in original tarball )
#   become: yes
#   ansible.builtin.shell: "chown --preserve-root -R {{ beacon2ri_user }}:{{ beacon2ri_user }} {{ beacon2ri_build_dir }}"

# - name: Build¦ make beacon2ri
#   become: yes
#   become_flags: "-u {{ beacon2ri_user }}"
#   ansible.builtin.command: "make -j4"
#   args:
#     chdir: "{{ beacon2ri_build_dir }}/{{ binaries_extracted.files[0] }}"

# - name: Build¦ install beacon2ri
#   become: yes
#   ansible.builtin.command: "make install"
#   args:
#     chdir: "{{ beacon2ri_build_dir }}/{{ binaries_extracted.files[0] }}"
