---
# tasks file for beacon2ri

###
# install docker (+ compose plugin)
# install git
# optionally install psfmd


- name: register os_family variable
  ansible.builtin.set_fact:
    os_family: "{{ ansible_facts['os_family'] | default('Suse') }}"
  tags: deps

- name: Info¦ os_family
  ansible.builtin.debug:
    msg: "{{ os_family }}"

- include_tasks:
    file: "deps/{{ os_family }}.yml"
    apply:
      tags: deps
  tags: deps

- import_tasks: user_wrangler.yml
  tags: user

- import_tasks: download_install.yml
  tags: install

- import_tasks: docker_plugin.yml
  tags: [ install, docker, plugin ]

# - import_tasks: post_install.yml
#   tags: post

- import_tasks: beacon2-ri-api/main.yml
  tags: [ build, config, install, quirks ]

- import_tasks: beacon2-ri-tools/quirks/pre-build.yml
  tags: [ install, quirks, tools-quirks ]

- import_tasks: beacon2-ri-tools/build.yml
  tags: [ build, tools-build ]
