---
- name: Ensure system dependencies 
  become: yes
  register: packages_installed
  ansible.builtin.package:
    state: present
    update_cache: yes
    name:
      - docker
      - docker-bash-completion
      - git
      - python3-pip
      # - tar
      # - gzip
      # - unzip
      # - man

- name: Info¦ packages installed?
  ansible.builtin.debug:
    msg: "{{ packages_installed }}"
