---
- name: Ensure system dependencies 
  become: yes
  register: packages_installed
  ansible.builtin.package:
    state: present
    update_cache: yes
    name:
      - docker
      - docker-bash-completion
      # - tar
      # - gzip
      # - unzip
      # - man

- name: Info¦ packages installed?
  ansible.builtin.debug:
    msg: "{{ packages_installed }}"

# - name: Install devel_basis (Build Essential)
#   become: yes
#   register: dev_toolchain
#   community.general.zypper:
#     update_cache: yes
#     state: present
#     type: pattern
#     name:
#       - devel_basis
#       # - devel_tcl

# - name: Info¦ dev toolchain installed?
#   ansible.builtin.debug:
#     msg: "{{ dev_toolchain }}"
